### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by mati4458** [m1c1b/escape-from-vires#1]
Hello,
I have built package in Maven and I do have .jar file with dependencies, as shown below. But I don't know where am I supposed to execute export command to set WAVES_SEED variable.
![image](https://user-images.githubusercontent.com/14836704/202850224-20f9a4b9-2a8a-44c2-bd41-8bcde4d4e7b4.png)
![image](https://user-images.githubusercontent.com/14836704/202854697-96e523a3-4156-4159-b549-260f056222e0.png)
![image](https://user-images.githubusercontent.com/14836704/202850425-2d45b196-ec19-46ac-a9a4-c89420977927.png)
![image](https://user-images.githubusercontent.com/14836704/202850480-51f3a4ee-8b18-4eee-9755-041275b64ee1.png)
![image](https://user-images.githubusercontent.com/14836704/202850491-112becef-0c8e-426c-bf95-5ab23b74d87c.png)

**Comment by m1c1b** [comment]
Hello! As I can see you have a wrong version of JVM, take current LTS version from [here](https://github.com/graalvm/graalvm-ce-builds/releases) for example (Java 17).

If you run app from windows cmd you shoud set env by command `set WAVES_SEED=seed` before `java -jar` command.
